---
abstract: 'parser of boolean expressions'
author:
  - 'Ruslan Zakirov <ruz@cpan.org>, Robert Spier <rspier@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-BooleanLogic
no_index:
  directory:
    - inc
    - t
requires:
  Regexp::Common: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: '0.10'
